version: 2.1
orbs:
  continuation: circleci/continuation@0.3.1
  node: circleci/node@5.0.2
setup: true
jobs:
  generate-config:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          app-dir: .circleci/dynamic
      - run:
          name: Generate config
          #command: node .circleci/dynamic/index.js
          command: npm start --prefix .circleci/dynamic
      - continuation/continue:
          configuration_path: ./dynamicConfig.yml
          
  test-containers-job:
    resource_class: small
    docker: 
      - image: cimg/base:stable
    
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          command: find /
  echo_params:
    docker: 
      - image: cimg/base:stable
    parameters:
      param1:
        type: string
      param2:
        type: string
    steps:
      - run:
          command: echo "p1" <<parameters.param1 >> "p2" <<parameters.param2>>
workflows:
  #dynamic-workflow:
  #  jobs:
  #    - generate-config
  test-containers:
    jobs:
      # - test-containers-job
      - echo_params:
          matrix:
            parameters:
              param1: [p1, p2, p3]
          param2: << parameters.param1 >>