version: 2.1

jobs:
  greeting:
    docker:
    - image: cimg/base:2023.01
    parameters:
      to:
        type: string
        default: default_to
    steps:
    - run: echo hello <<parameters.to>>


workflows:
  greet-all:
    jobs:
    - greeting:
        matrix:
          parameters:
            to: [angel, pedro, juan]
