version: 2.1
orbs:
  continuation: circleci/continuation@0.3.1
  node: circleci/node@5.0.2
setup: true
jobs:
  generate-config:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          app-dir: .circleci/dynamic
      - run:
          name: Generate config
          #command: node .circleci/dynamic/index.js
          command: npm start --prefix .circleci/dynamic
      - continuation/continue:
          configuration_path: ./dynamicConfig.yml
  test-containers-job
    docker: cimg/base
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          command: find /
workflows:
  dynamic-workflow:
    jobs:
      - generate-config
  test-containers:
    jobs:
      - test-containers-job