version: 2.1

jobs:
  greeting:
    docker:
    - image: cimg/base:2023.01
    parameters:
      to:
        type: enum
        enum:
          - angel
          - pedro
          - chanquete
    steps:
    - run: ls /nonexistentdir


workflows:
  greet-all:
    jobs:
    - greeting:
        name: greeting job with path = $CIRCLE_BRANCH
        to: angel
