version: 2.1
aliases:
  - &var1 value1
  - &var2 value2
  - &arr
     - arr_value1
     - arr_value2

jobs:
  greeting:
    docker:
    - image: cimg/base:2023.01
    parameters:
      var_name:
        type: enum
        enum:
          - var1
          - var2
    steps:
    - run: echo <<parameters.var_name>>
    - run: echo $ENV_VAR
    environment:
      - ENV_VAR: *arr


workflows:
  greet-all:
    jobs:
    - greeting:
        name: greeting job with path = $CIRCLE_BRANCH
        var_name: var1
